name: RPi Zero 2 binary

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release-armhf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'
      - run: |
          env GOOS=linux GOARCH=arm GOARM=7 go build -o coddabot-armhf cmd/bot/main.go
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: coddabot-armhf